// Auto-generated by tools/sf2_to_cpp.py  -  do not edit by hand.
// SoundFont: SYNTHGMS.sf2  (1090324 bytes)
#pragma once
#include <stdint.h>

extern const unsigned char g_sf2_SYNTHGMS[];   // raw .sf2 bytes, lives in flash
extern const unsigned long  g_sf2_SYNTHGMS_len; // = 1090324
