// Auto-generated by tools/sf2_to_cpp.py  -  do not edit by hand.
// SoundFont: VintageDreams.sf2  (314640 bytes)
#pragma once
#include <stdint.h>

extern const unsigned char g_sf2_VintageDreams[];   // raw .sf2 bytes, lives in flash
extern const unsigned long  g_sf2_VintageDreams_len; // = 314640
