#!/usr/bin/env python3
# ============================================================================
#  sf2_to_cpp.py  -  Bake a .sf2 SoundFont into a C++ source file.
#
#  The RP2040 maps flash into the CPU address space (XIP), so a plain
#  `const unsigned char[]` lives in flash and is directly readable by the
#  synth with ZERO RAM cost for the sample data.  This script turns any
#  SoundFont into such an array plus a tiny header describing it.
#
#  Usage:
#     python3 tools/sf2_to_cpp.py soundfonts/VintageDreams.sf2 \
#             --name VintageDreams --out .
#
#  Produces  Soundfont_<name>.cpp  and  Soundfont_<name>.h  next to --out.
# ============================================================================
import argparse, os, sys, textwrap

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sf2", help="input .sf2 file")
    ap.add_argument("--name", required=True, help="C identifier base, e.g. VintageDreams")
    ap.add_argument("--out", default=".", help="output directory")
    a = ap.parse_args()

    data = open(a.sf2, "rb").read()
    sym  = "g_sf2_" + a.name
    mac  = "FONT_" + a.name.upper()      # matches the selector in Config.h
    cpp  = os.path.join(a.out, f"Soundfont_{a.name}.cpp")
    hdr  = os.path.join(a.out, f"Soundfont_{a.name}.h")

    # Header ------------------------------------------------------------------
    with open(hdr, "w") as f:
        f.write(textwrap.dedent(f"""\
            // Auto-generated by tools/sf2_to_cpp.py  -  do not edit by hand.
            // SoundFont: {os.path.basename(a.sf2)}  ({len(data)} bytes)
            #pragma once
            #include <stdint.h>

            extern const unsigned char {sym}[];   // raw .sf2 bytes, lives in flash
            extern const unsigned long  {sym}_len; // = {len(data)}
        """))

    # Body --------------------------------------------------------------------
    with open(cpp, "w") as f:
        f.write(f"// Auto-generated by tools/sf2_to_cpp.py  -  do not edit by hand.\n")
        f.write(f'#include "Soundfont_{a.name}.h"\n')
        f.write(f'#include "Config.h"\n')
        # Only emit the (large) array when this font is the selected one, so the
        # Arduino build does not link unused fonts into flash.
        f.write(f"#ifndef {mac}\n#define {mac} 0\n#endif\n")
        f.write(f"#if {mac}\n")
        # `const` (not in RAM) so the linker keeps it in flash / .rodata.
        f.write(f"const unsigned char {sym}[] = {{\n")
        line = []
        for i, b in enumerate(data):
            line.append(f"0x{b:02x},")
            if len(line) == 20:
                f.write("  " + "".join(line) + "\n")
                line = []
        if line:
            f.write("  " + "".join(line) + "\n")
        f.write("};\n")
        f.write(f"const unsigned long {sym}_len = {len(data)};\n")
        f.write(f"#endif  // {mac}\n")

    print(f"wrote {cpp} and {hdr}  ({len(data)} bytes)")

if __name__ == "__main__":
    sys.exit(main())
